version: '3.7'
services:
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - '.:/web'
      - '/web/node_modules'
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    stdin_open: true
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./client/:/usr/src/app
    ports:
      - '5000:5000'